name: Triage tasks

on: pull_request_target

env:
  GH_REPO: ${{ github.repository }}
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: "triage-${{ github.event.number }}"
  cancel-in-progress: true

permissions: {}

jobs:
  upload-metadata:
    permissions:
      contents: read
    if: always() && github.repository_owner == 'Homebrew'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        with:
          name: event_payload
          path: ${{ github.event_path }}

  workflows-label:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    if: always() && github.repository_owner == 'Homebrew'
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request changed files
        id: files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.number }}
        run: |
          workflow_modified="$(
            gh api \
              --header 'Accept: application/vnd.github+json' \
              --header 'X-GitHub-Api-Version: 2022-11-28' \
              "repos/$GITHUB_REPOSITORY/pulls/$PR/files" \
              --jq 'any(.[].filename; startswith(".github/workflows"))'
          )"
          # Fail closed.
          echo "workflow_modified=${workflow_modified:-true}" >> "${GITHUB_OUTPUT}"

      # Wait briefly in case of failure to make sure we don't end up
      # hitting the same API error when trying `gh pr edit`.
      - if: failure()
        run: sleep 30

      - name: Label PR
        if: always() && fromJson(steps.files.outputs.workflow_modified)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.number }}
        run: gh pr edit --add-label workflows "$PR" --repo "$GITHUB_REPOSITORY"

  limit-pull-requests:
    if: >
      always() && github.repository_owner == 'Homebrew' &&
      (github.event_name == 'pull_request_target' &&
       github.event.action == 'opened')
    permissions:
      contents: read
      issues: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: Homebrew/actions/limit-pull-requests@master
        with:
          except-users: |
            BrewTestBot
          comment-limit: 15
          comment: |
            Hi, thanks for your contribution to Homebrew! :heart:

            You already have >=15 open pull requests, so please get them ready to be merged or close them before you open more. If CI fails on any of them, please fix it or ask for help doing so.

            If you are performing simple version bumps, @BrewTestBot automatically bumps [a list of formulae](https://github.com/${{ github.repository }}/blob/HEAD/.github/autobump.txt) so you don't need to. Please take a look at issues and pull requests labelled https://github.com/${{ github.repository }}/labels/help%20wanted and see if you can help to fix any of them. Thanks!
          close-limit: 30
          close: true

  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: Check commit format
        if: >
          github.actor != 'BrewTestBot' &&
          !contains(github.event.pull_request.labels.*.name, 'CI-published-bottle-commits')
        uses: Homebrew/actions/check-commit-format@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Label pull request
        uses: Homebrew/actions/label-pull-requests@master
        if: always()
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          def: |
            - label: new formula
              status: added
              path: Formula/.+
              allow_any_match: true

            - label: marked for removal/rejection
              status: removed
              path: Formula/.+

            - label: no ARM bottle
              path: Formula/.+
              content: '\n    sha256.* (?!.*(?:arm64_|_linux)).+: +"[a-fA-F0-9]+"\n'
              missing_content: '\n    sha256.* (arm64_.+|all): +"[a-fA-F0-9]+"\n'

            - label: no Linux bottle
              path: Formula/.+
              content: \n  bottle do\n
              missing_content:
                - '\n    sha256.* x86_64_linux: +"[a-fA-F0-9]+"\n'
                - '\n    sha256.* all: +"[a-fA-F0-9]+"\n'
                - depends_on :macos

            - label: formula deprecated
              path: Formula/.+
              content: \n  deprecate!.*\n

            - label: formula disabled
              path: Formula/.+
              content: \n  disable!.*\n

            - label: legacy
              path: Formula/.+@.+
              except:
                - Formula/b/bash-completion@2.rb
                - Formula/i/icu4c@76.rb
                - Formula/lib/libxml++@5.rb
                - Formula/o/openssl@3.rb
                - Formula/p/postgresql@17.rb
                - Formula/p/python@3.13.rb
                - Formula/p/python-gdbm@3.13.rb
                - Formula/p/python-tk@3.13.rb

            - label: missing license
              path: Formula/.+
              missing_content: \n  license .+\n

            - label: deprecated license
              path: Formula/.+
              content: license .*"(GPL|LGPL|AGPL|GFDL)-[0-9].[0-9][+]?".*

            - label: boost
              path: Formula/.+
              content: depends_on "boost(@[0-9.]+)?"

            - label: ffmpeg
              path: Formula/.+
              content: depends_on "ffmpeg(@[0-9.]+)?"

            - label: go
              path: Formula/.+
              content: depends_on "go(@[0-9.]+)?"

            - label: haskell
              path: Formula/.+
              content: depends_on "(ghc|haskell-stack)(@[0-9.]+)?"

            - label: icu4c
              path: Formula/.+
              content: depends_on "icu4c(@[0-9.]+)?"

            - label: java
              path: Formula/.+
              content: depends_on "openjdk(@[0-9.]+)?"

            - label: linux-only
              path: Formula/.+
              content: depends_on :linux

            - label: macos-only
              path: Formula/.+
              content: depends_on :macos

            - label: lua
              path: Formula/.+
              content: depends_on "(lua|luajit|luajit-openresty)(@[0-9.]+)?"

            - label: nodejs
              path: Formula/.+
              content: depends_on "node(@[0-9.]+)?"

            - label: ocaml
              path: Formula/.+
              content: depends_on "ocaml(@[0-9.]+)?"

            - label: perl
              path: Formula/.+
              content: (depends_on|uses_from_macos) "perl(@[0-9.]+)?"

            - label: php
              path: Formula/.+
              content: (depends_on|uses_from_macos) "php(@[0-9.]+)?"

            - label: python
              path: Formula/.+
              content: (depends_on|uses_from_macos) "python(@[0-9.]+)?"
              missing_content: (depends_on|uses_from_macos) "python(@[0-9.]+)?" => \[?:(build|test)

            - label: ruby
              path: Formula/.+
              content: (depends_on|uses_from_macos) "ruby(@[0-9.]+)?"

            - label: rust
              path: Formula/.+
              content: depends_on "rust(@[0-9.]+)?"

            - label: zig
              path: Formula/.+
              content: depends_on "zig(@[0-9.]+)?"

            - label: dotnet
              path: Formula/.+
              content: depends_on "dotnet(@[0-9.]+)?"

            - label: swift
              path: Formula/.+
              content: system "swift", "build"

            - label: long build
              path: "Formula/.+/(\
                agda|\
                apache-pulsar|\
                arangodb|\
                aws-sdk-cpp|\
                cbmc|\
                cp2k|\
                deno|\
                dotnet|\
                emscripten|\
                envoy|\
                gcc|\
                ghc|\
                graph-tool|\
                gstreamer|\
                haskell-language-server|\
                libtensorflow|\
                mame|\
                metashell|\
                mlkit|\
                mpich|\
                node|\
                octave|\
                opencascade|\
                openvino|\
                pcl|\
                ponyc|\
                pytorch|\
                qt|\
                root|\
                rtabmap|\
                rust|\
                souffle|\
                swift|\
                texlive|\
                v8|\
                vtk\
                )(@[0-9.]+)?.rb"
              keep_if_no_match: true
              allow_any_match: true

            - label: long dependent tests
              path: "Formula/.+/(\
                aom|\
                at-spi2-core|\
                boost|\
                brotli|\
                c-ares|\
                dav1d|\
                freetype|\
                gcc|\
                ghc|\
                glib|\
                gsettings-desktop-schemas|\
                gtk\\+3|\
                harfbuzz|\
                highway|\
                hwloc|\
                icu4c|\
                imath|\
                jasper|\
                jpeg-turbo|\
                jpeg-xl|\
                libcap|\
                libgcrypt|\
                libgpg-error|\
                libidn2|\
                libmicrohttpd|\
                librist|\
                libnghttp2|\
                libomp|\
                libpng|\
                libtool|\
                libunistring|\
                mpfr|\
                mpg123|\
                node|\
                numpy|\
                openblas|\
                openjpeg|\
                p11-kit|\
                pango|\
                pcre2|\
                rav1e|\
                rust|\
                shared-mime-info|\
                suite-sparse|\
                qt|\
                readline|\
                unbound|\
                xz|\
                zstd\
                ).rb"
              keep_if_no_match: true
              allow_any_match: true

            - label: CI-build-dependents-from-source
              path:
                - 'Formula/.+/(cabal-install|docbook-xsl|emscripten|erlang|ocaml|ocaml-findlib|ocaml-num|openjdk|rust)\.rb'
                - 'Aliases/(ghc|go)(@[0-9.]+)?$'
              missing_content: '\n  revision [0-9]+\n'
              keep_if_no_match: true
              allow_any_match: true

            - label: CI-skip-recursive-dependents
              path: Formula/.+/(ca-certificates|curl|gettext|openssl@3|sqlite|systemd).rb
              keep_if_no_match: true

            - label: CI-linux-self-hosted
              path: "Formula/.+/(\
                dart-sdk|\
                envoy|\
                qt(@5)?|\
                teleport|\
                texlive\
                ).rb"
              keep_if_no_match: true
              allow_any_match: true

            - label: CI-linux-self-hosted-deps
              path: "Formula/.+/(\
                alsa-lib|\
                glib|\
                libcap|\
                libva|\
                libxml2|\
                python@3.12|\
                wayland-protocols|\
                zlib|\
                ).rb"
              keep_if_no_match: true
              allow_any_match: true

            - label: bump-formula-pr
              pr_body_content: Created with `brew bump-formula-pr`

            - label: pip-audit
              pr_body_content: Created by `brew-pip-audit`

            - label: autobump
              path: \.github/autobump\.txt
              allow_any_match: true
